before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  ldflags:
  - -s -w -X github.com/dominodatalab/ranchhand/cmd.version={{.Version}} -X github.com/dominodatalab/ranchhand/cmd.gitCommit={{.FullCommit}} -X github.com/dominodatalab/ranchhand/cmd.buildDate={{.Date}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
