version: 2.1
executors:
  builder:
    docker:
    - image: circleci/golang:1.12
    environment:
      GORELEASER_VERSION: v0.102.0
jobs:
  release:
    executor: builder
    steps:
    - checkout
    - run: curl -sL https://git.io/goreleaser | VERSION=${GORELEASER_VERSION} bash
workflows:
  version: 2
  release:
    jobs:
    - release:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
